parameters:
    video_provider_bundle.provider: ThePlatform

services:
    acilia.video_provider:
        class: Acilia\Bundle\VideoProviderBundle\Service\VideoProviderService
        arguments:
            - %video_provider_bundle.provider%
            - {user: %video_provider_bundle.user%, password: %video_provider_bundle.password%}
